#!/bin/sh
#
#This is an example script to execute a parallel job with OpenFOAM
# ! Be sure to have decompose using decomposePar before submitting this script
#
#These commands set up the Grid Environment for your job:
# Output folder for the journal file
#PBS -o /nfs/home/ofoam10/OpenFOAM/ofoam10-6/run/CarAero/SemesterProjekt/Drivaer_modified 
#PBS -j oe
# Name of the job
#PBS -N DrivAer_modified
#PBS -q batch
#PBS -l nodes=1:ppn=6:buddies
# E-mail address at which notification will be sent
#PBS -M y.beis@hotmail.com
#PBS -m abe

# Load OpenFOAM-6
source /nfs/etc/bashrc
OF60
# Change the current directory to the case directory
cd /nfs/home/ofoam10/OpenFOAM/ofoam10-6/run/CarAero/SemesterProjekt/Drivaer_modified
# Execute interFoam on the current case directory
mpiexec renumberMesh -parallel -overwrite > log.solver
